# Generated by Django 5.2.14 on 2026-05-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0011_alter_presenca_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DocumentoEvento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                        ('arquivo_url', models.URLField(max_length=500, verbose_name='URL do Arquivo (Drive)')),
                        ('restrito_delegados', models.BooleanField(default=False, verbose_name='Restrito a Delegados')),
                        ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='eventos.evento')),
                    ],
                    options={
                        'verbose_name': 'Documento do Evento',
                        'verbose_name_plural': 'Documentos do Evento',
                    },
                ),
                migrations.CreateModel(
                    name='Sessao',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=200, verbose_name='Nome da Sessão')),
                        ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                        ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='eventos.evento')),
                    ],
                    options={
                        'verbose_name': 'Sessão',
                        'verbose_name_plural': 'Sessões',
                        'ordering': ['data_hora'],
                    },
                ),
                migrations.CreateModel(
                    name='Presenca',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                        ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_em_sessoes', to='eventos.inscricao')),
                        ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='hub.sessao')),
                    ],
                    options={
                        'verbose_name': 'Presença',
                        'verbose_name_plural': 'Presenças',
                        'unique_together': {('sessao', 'inscricao')},
                    },
                ),
            ],
            database_operations=[]
        )
    ]
