# Generated by Django 5.2.14 on 2026-05-11 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentoevento',
            options={'ordering': ['-is_ata_sessao', 'tipo__ordem', 'ordem', '-data_disponibilizacao'], 'verbose_name': 'Documento do Evento', 'verbose_name_plural': 'Documentos do Evento'},
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='data_disponibilizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Disponibilização'),
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='is_ata_sessao',
            field=models.BooleanField(default=False, verbose_name='É Ata da Sessão Atual?'),
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem na Categoria'),
        ),
        migrations.AlterField(
            model_name='documentoevento',
            name='restrito_delegados',
            field=models.BooleanField(default=True, verbose_name='Restrito a Delegados'),
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='hub.tipodocumento'),
        ),
    ]
