# Generated by Django 5.2.14 on 2026-05-23 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_presenca_unique_together_and_more'),
        ('sessoes', '0005_mesa_extras_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventolog',
            index=models.Index(fields=['sessao_id', 'timestamp'], name='log_sessao_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='membrodamesa',
            index=models.Index(fields=['sessao_id', 'encerrou_em'], name='mesa_sessao_ativa_idx'),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['sessao_id', 'presente'], name='presenca_sessao_presente_idx'),
        ),
        migrations.AddIndex(
            model_name='sessao',
            index=models.Index(fields=['evento_id', 'status'], name='sessao_evento_status_idx'),
        ),
        migrations.AddIndex(
            model_name='votacao',
            index=models.Index(fields=['sessao_id', 'status'], name='votacao_sessao_status_idx'),
        ),
    ]
