# Generated by Django 5.2.14 on 2026-07-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_presenca_unique_together_and_more'),
        ('sessoes', '0006_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designado_em', models.DateTimeField(auto_now_add=True)),
                ('designado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_designados', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador_presenca', to='eventos.inscricao')),
            ],
            options={
                'verbose_name': 'Operador de Presença',
                'verbose_name_plural': 'Operadores de Presença',
            },
        ),
    ]
