# Generated by Django 5.2.14 on 2026-05-25 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0011_alter_presenca_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEmblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('icone', models.CharField(max_length=10, verbose_name='Ícone')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('comportamento', 'Comportamento e Postura'), ('servico', 'Serviço e Dedicação'), ('democratico', 'Participação Democrática'), ('especial', 'Especial')], max_length=30, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogo_emblemas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Emblema',
                'verbose_name_plural': 'Catálogo de Emblemas',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('icone', models.CharField(max_length=10, verbose_name='Ícone')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('comportamento', 'Comportamento e Postura'), ('servico', 'Serviço e Dedicação'), ('democratico', 'Participação Democrática'), ('especial', 'Especial')], max_length=30, verbose_name='Categoria')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Rascunho'), (2, 'Publicado')], default=1, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emblemas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emblemas', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Emblema',
                'verbose_name_plural': 'Emblemas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EmblemaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concedido_em', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('concedido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emblemas_concedidos', to=settings.AUTH_USER_MODEL)),
                ('emblema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='emblemas.emblema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emblemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emblema do Usuário',
                'verbose_name_plural': 'Emblemas dos Usuários',
                'indexes': [models.Index(fields=['usuario', 'concedido_em'], name='emblemas_em_usuario_a0ecef_idx'), models.Index(fields=['usuario', 'notificado'], name='emblemas_em_usuario_730494_idx')],
                'unique_together': {('emblema', 'usuario')},
            },
        ),
    ]
