# Generated by Django 5.2.14 on 2026-05-08 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.IntegerField(choices=[(1, 'Administrativo (Congressos, CEs)'), (2, 'Comunhão (Acampamentos, Encontros)')], default=2, verbose_name='Categoria')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos/banners/', verbose_name='Banner')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('arquivo_url', models.URLField(verbose_name='URL do Arquivo (Drive)')),
                ('restrito_delegados', models.BooleanField(default=False, verbose_name='Restrito a Delegados')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Documento do Evento',
                'verbose_name_plural': 'Documentos do Evento',
            },
        ),
        migrations.CreateModel(
            name='CampoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('tipo_campo', models.IntegerField(choices=[(1, 'Texto'), (2, 'Número'), (3, 'Seleção (Dropdown)'), (4, 'Checkbox')], default=1, verbose_name='Tipo do Campo')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('opcoes', models.TextField(blank=True, help_text='Apenas para campos de Seleção', verbose_name='Opções (separadas por vírgula)')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_evento', models.IntegerField(choices=[(1, 'Delegado (Efetivo)'), (2, 'Ex-Officio'), (3, 'Correspondente'), (4, 'Visitante')], default=4, verbose_name='Papel no Evento')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aprovado'), (3, 'Rejeitado')], default=1, verbose_name='Status')),
                ('credential_url', models.URLField(blank=True, help_text='Obrigatório para Delegados', null=True, verbose_name='URL da Credencial (Drive)')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='eventos.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='RespostaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(verbose_name='Resposta')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.campoevento')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='eventos.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Sessão')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_em_sessoes', to='eventos.inscricao')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='eventos.sessao')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'unique_together': {('sessao', 'inscricao')},
            },
        ),
    ]
