# Generated by Django 5.2.14 on 2026-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_inscricao_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vagas',
            field=models.PositiveIntegerField(default=0, help_text='Deixe 0 para vagas ilimitadas', verbose_name='Quantidade de Vagas'),
        ),
    ]
