# Generated by Django 5.2.14 on 2026-05-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricoes_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricoes_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início das Inscrições'),
        ),
    ]
