# Generated by Django 5.2.14 on 2026-05-09 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_inscricoes_fim_evento_inscricoes_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chave PIX para Recebimento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='instrucoes_pagamento',
            field=models.TextField(blank=True, verbose_name='Instruções de Pagamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Inscrição'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='credencial_validada',
            field=models.BooleanField(default=False, verbose_name='Credencial Validada'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pagamento Confirmado'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='credential_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Credencial (Drive)'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aprovado'), (3, 'Rejeitado')], default=1, verbose_name='Status Final'),
        ),
    ]
