# Generated by Django 5.2.14 on 2026-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_chave_pix_evento_instrucoes_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_financeiro',
            field=models.IntegerField(choices=[(0, 'Gratuito'), (1, 'Manual (PIX)'), (2, 'InfinitePay')], default=1, verbose_name='Tipo Financeiro'),
        ),
    ]
