# Generated by Django 5.2.14 on 2026-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_tipo_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='infinitepay_link_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='InfinitePay Invoice Slug'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='infinitepay_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Pagamento InfinitePay'),
        ),
    ]
