# Generated by Django 5.2.14 on 2026-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_inscricao_infinitepay_link_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='credential_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Credencial (Drive)'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='infinitepay_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Pagamento InfinitePay'),
        ),
    ]
