# Generated by Django 5.2.14 on 2026-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_inscricao_credential_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoevento',
            name='arquivo_url',
            field=models.URLField(max_length=500, verbose_name='URL do Arquivo (Drive)'),
        ),
    ]
