# Generated by Django 5.2.14 on 2026-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_documentoevento_arquivo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
