# Generated by Django 5.2.14 on 2026-05-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_inscricao_motivo_rejeicao'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='DocumentoEvento',
                    table='hub_documentoevento',
                ),
                migrations.AlterModelTable(
                    name='Sessao',
                    table='hub_sessao',
                ),
                migrations.AlterModelTable(
                    name='Presenca',
                    table='hub_presenca',
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='presenca',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='presenca',
                    name='inscricao',
                ),
                migrations.RemoveField(
                    model_name='presenca',
                    name='sessao',
                ),
                migrations.RemoveField(
                    model_name='sessao',
                    name='evento',
                ),
                migrations.DeleteModel(
                    name='DocumentoEvento',
                ),
                migrations.DeleteModel(
                    name='Presenca',
                ),
                migrations.DeleteModel(
                    name='Sessao',
                ),
            ]
        )
    ]
