# Generated by Django 5.2.14 on 2026-05-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Inclua o DDD (ex: 11988887777)', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
